#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v12
# autospec commit: 5899074
#
Name     : aardvark-dns
Version  : 1.11.0
Release  : 3
URL      : https://github.com/containers/aardvark-dns/archive/refs/tags/v1.11.0.tar.gz
Source0  : https://github.com/containers/aardvark-dns/archive/refs/tags/v1.11.0.tar.gz
Source1  : https://github.com/containers/aardvark-dns/releases/download/v1.11.0/aardvark-dns-v1.11.0-vendor.tar.gz
Summary  : Authoritative DNS server for A/AAAA container records
Group    : Development/Tools
License  : Apache-2.0 MIT Unicode-DFS-2016 Zlib
Requires: aardvark-dns-libexec = %{version}-%{release}
Requires: aardvark-dns-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# aardvark-dns
Aardvark-dns is an authoritative dns server for `A/AAAA` container records. It can forward other requests
to configured resolvers.

%package libexec
Summary: libexec components for the aardvark-dns package.
Group: Default
Requires: aardvark-dns-license = %{version}-%{release}

%description libexec
libexec components for the aardvark-dns package.


%package license
Summary: license components for the aardvark-dns package.
Group: Default

%description license
license components for the aardvark-dns package.


%prep
%setup -q -n aardvark-dns-1.11.0
cd %{_builddir}
tar xf %{_sourcedir}/aardvark-dns-v1.11.0-vendor.tar.gz
cd %{_builddir}/aardvark-dns-1.11.0
mkdir -p ./vendor
cp -r %{_builddir}/vendor/* %{_builddir}/aardvark-dns-1.11.0/./vendor
## copy_prepend content
mkdir -p .cargo
cat << EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
EOF
## copy_prepend end

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719610017
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719610017
rm -rf %{buildroot}
## install_prepend content
export PREFIX=/usr
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/aardvark-dns
cp %{_builddir}/aardvark-dns-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/vendor/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/vendor/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/vendor/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/arc-swap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/arc-swap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/3c2cc74b6c4f504a5106f85ad6ff1a5b2e46b18b || :
cp %{_builddir}/vendor/async-trait/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/async-trait/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/vendor/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/bytes/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/2510927d07430a2092720e8f4a5287043f75e8d3 || :
cp %{_builddir}/vendor/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/cfg_aliases/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/vendor/chrono/LICENSE.txt %{buildroot}/usr/share/package-licenses/aardvark-dns/c145b1a607ecf06aed81f1d04a65c2e43dffdc63 || :
cp %{_builddir}/vendor/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/data-encoding/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/7963d112b803d110d3e75e932c052284fd208629 || :
cp %{_builddir}/vendor/deranged/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/vendor/deranged/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/vendor/endian-type/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/a4692c5ae019f8bf1695b9c8b4e0ccae899b6e80 || :
cp %{_builddir}/vendor/enum-as-inner/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/enum-as-inner/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/c71b43677c4ac8205f6eb573a073ea8e6df60c91 || :
cp %{_builddir}/vendor/error-chain/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/error-chain/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/0b6960112e4f98ee7d2ede41f5214f40d9be5ff0 || :
cp %{_builddir}/vendor/flume/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/77756d7dbf04c00fbc83e67bc9114785421aecf3 || :
cp %{_builddir}/vendor/flume/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/a74c5e048f9ed570eb892f81ca5daf05936475b0 || :
cp %{_builddir}/vendor/form_urlencoded/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/form_urlencoded/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/vendor/futures-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-io/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-io/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-sink/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-sink/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-task/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-task/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-util/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/vendor/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/vendor/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/hickory-client/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/70b1900df6c7d54cfc2187022ee179097a06e7c8 || :
cp %{_builddir}/vendor/hickory-proto/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/2216ec5c9128563dd71b9a56e377c827d0192834 || :
cp %{_builddir}/vendor/hickory-server/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/2216ec5c9128563dd71b9a56e377c827d0192834 || :
cp %{_builddir}/vendor/hostname/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/2ae89abd889d4355e46e01376881155e899d50ca || :
cp %{_builddir}/vendor/iana-time-zone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/vendor/iana-time-zone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/vendor/idna-0.4.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/idna-0.4.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/ipnet/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/bb92c62835916e922667b4fe181beed0e6efca91 || :
cp %{_builddir}/vendor/ipnet/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4f8ab673f6e2ae6c7bb2910d7f38838c18c12178 || :
cp %{_builddir}/vendor/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/vendor/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/vendor/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/match_cfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/match_cfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/mio/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/27541df8e6d877c3912bbe4c48711f36e826cc5b || :
cp %{_builddir}/vendor/nibble_vec/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/bb8a9c551056a487e6bde6b31115ae45a9b9b802 || :
cp %{_builddir}/vendor/nix/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/vendor/num-conv/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/c54e008a9d57391b98e60b14c8dc524acd7b2df9 || :
cp %{_builddir}/vendor/num-conv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/18f13b198a4a6248c4ce96a0f82de708bc68fd0c || :
cp %{_builddir}/vendor/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563 || :
cp %{_builddir}/vendor/num_threads/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/d7922ed0153e53eb7d63ea3fcae1040472c67679 || :
cp %{_builddir}/vendor/num_threads/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/31e133ad6e12ed607bafa6decc49865e76e2a8e0 || :
cp %{_builddir}/vendor/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/pin-project-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/vendor/pin-project-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/pin-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/a2f60339450a52e61c6c1e27dc44bd1e671ad28e || :
cp %{_builddir}/vendor/pin-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/91abce61ea0c1c313bb5ba31f04196490960a479 || :
cp %{_builddir}/vendor/powerfmt/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/2ef5dbf415191a7880f5baa5ab1997a807967c13 || :
cp %{_builddir}/vendor/powerfmt/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/5641ab41a62889b9a22161d95f174fc889dd9660 || :
cp %{_builddir}/vendor/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/vendor/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/vendor/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/quick-error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/quick-error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/1a00693a4e6240a4d040d1a1f76efaf50f20b8dd || :
cp %{_builddir}/vendor/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/radix_trie/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/bb8a9c551056a487e6bde6b31115ae45a9b9b802 || :
cp %{_builddir}/vendor/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/aardvark-dns/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/vendor/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/aardvark-dns/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/vendor/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/aardvark-dns/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/resolv-conf/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/resolv-conf/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/f2d93b43d5bc8666a7978f9e71d7477d730a10c4 || :
cp %{_builddir}/vendor/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/vendor/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/signal-hook-registry/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/signal-hook-registry/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/vendor/signal-hook/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/signal-hook/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/vendor/slab/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/96f019e8abadc7a87b330a697504d874a1c06268 || :
cp %{_builddir}/vendor/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/vendor/socket2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/socket2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/spin/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/42631684b818350022ee962eef0a9592b159d838 || :
cp %{_builddir}/vendor/strsim/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/vendor/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/syslog/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/e7b32657d4608cb4a57afa790801ecb9c2a037f5 || :
cp %{_builddir}/vendor/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/time-core/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/vendor/time-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/vendor/time-macros/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/vendor/time-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/vendor/time/LICENSE-Apache %{buildroot}/usr/share/package-licenses/aardvark-dns/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/vendor/time/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/vendor/tinyvec/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/aardvark-dns/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/vendor/tinyvec/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/aardvark-dns/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb || :
cp %{_builddir}/vendor/tinyvec/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/aardvark-dns/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/vendor/tinyvec_macros/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/aardvark-dns/8cc042e8e4b82c5532c72172a1988a74a599d4b5 || :
cp %{_builddir}/vendor/tinyvec_macros/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/aardvark-dns/86d193cb6b24df990cbbaf67c6a24fddbcb574c1 || :
cp %{_builddir}/vendor/tokio-macros/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/91b0ae81a1609fbc63e6ee539106bd0ce9f7e56a || :
cp %{_builddir}/vendor/tokio-util/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13 || :
cp %{_builddir}/vendor/tokio/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13 || :
cp %{_builddir}/vendor/tracing-attributes/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/tracing-core/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/tracing-core/src/spin/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/0956f8ac49e23a546fb113f711d7cdc0c3e98c85 || :
cp %{_builddir}/vendor/tracing/LICENSE %{buildroot}/usr/share/package-licenses/aardvark-dns/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/aardvark-dns/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd || :
cp %{_builddir}/vendor/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/aardvark-dns/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/vendor/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/aardvark-dns/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/vendor/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/vendor/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/aardvark-dns/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files libexec
%defattr(-,root,root,-)
/usr/libexec/podman/aardvark-dns

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aardvark-dns/03431277c040357c85596083ac918eb591ac04ac
/usr/share/package-licenses/aardvark-dns/067f31555f328efb78075174add7db97d98618c6
/usr/share/package-licenses/aardvark-dns/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/aardvark-dns/0956f8ac49e23a546fb113f711d7cdc0c3e98c85
/usr/share/package-licenses/aardvark-dns/0b6960112e4f98ee7d2ede41f5214f40d9be5ff0
/usr/share/package-licenses/aardvark-dns/13f55d9b7b3a769d76eab5d4a096f7ff24a017be
/usr/share/package-licenses/aardvark-dns/18f13b198a4a6248c4ce96a0f82de708bc68fd0c
/usr/share/package-licenses/aardvark-dns/1a00693a4e6240a4d040d1a1f76efaf50f20b8dd
/usr/share/package-licenses/aardvark-dns/2216ec5c9128563dd71b9a56e377c827d0192834
/usr/share/package-licenses/aardvark-dns/2510927d07430a2092720e8f4a5287043f75e8d3
/usr/share/package-licenses/aardvark-dns/27541df8e6d877c3912bbe4c48711f36e826cc5b
/usr/share/package-licenses/aardvark-dns/2ae89abd889d4355e46e01376881155e899d50ca
/usr/share/package-licenses/aardvark-dns/2ef5dbf415191a7880f5baa5ab1997a807967c13
/usr/share/package-licenses/aardvark-dns/31e133ad6e12ed607bafa6decc49865e76e2a8e0
/usr/share/package-licenses/aardvark-dns/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/aardvark-dns/39806df76979277073594a0c19005c3c7fb17221
/usr/share/package-licenses/aardvark-dns/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/aardvark-dns/3c2cc74b6c4f504a5106f85ad6ff1a5b2e46b18b
/usr/share/package-licenses/aardvark-dns/3c8e7847ca19c2bb00f4100c725810c04a1b56d6
/usr/share/package-licenses/aardvark-dns/42631684b818350022ee962eef0a9592b159d838
/usr/share/package-licenses/aardvark-dns/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/aardvark-dns/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/aardvark-dns/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/aardvark-dns/4f8ab673f6e2ae6c7bb2910d7f38838c18c12178
/usr/share/package-licenses/aardvark-dns/5641ab41a62889b9a22161d95f174fc889dd9660
/usr/share/package-licenses/aardvark-dns/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/aardvark-dns/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/aardvark-dns/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/aardvark-dns/59b5efd50c4508e7fa74828e7469187bbe5bd864
/usr/share/package-licenses/aardvark-dns/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/aardvark-dns/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/aardvark-dns/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/aardvark-dns/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/aardvark-dns/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/aardvark-dns/70b1900df6c7d54cfc2187022ee179097a06e7c8
/usr/share/package-licenses/aardvark-dns/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/aardvark-dns/75b9500512bb4d24722887e64a982c51e6bdcc4c
/usr/share/package-licenses/aardvark-dns/77756d7dbf04c00fbc83e67bc9114785421aecf3
/usr/share/package-licenses/aardvark-dns/7963d112b803d110d3e75e932c052284fd208629
/usr/share/package-licenses/aardvark-dns/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/aardvark-dns/86d193cb6b24df990cbbaf67c6a24fddbcb574c1
/usr/share/package-licenses/aardvark-dns/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/aardvark-dns/8cc042e8e4b82c5532c72172a1988a74a599d4b5
/usr/share/package-licenses/aardvark-dns/8e31d76c1073644a6e761836ac34a590fee47a83
/usr/share/package-licenses/aardvark-dns/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/aardvark-dns/91abce61ea0c1c313bb5ba31f04196490960a479
/usr/share/package-licenses/aardvark-dns/91b0ae81a1609fbc63e6ee539106bd0ce9f7e56a
/usr/share/package-licenses/aardvark-dns/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/aardvark-dns/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/aardvark-dns/96f019e8abadc7a87b330a697504d874a1c06268
/usr/share/package-licenses/aardvark-dns/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/aardvark-dns/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13
/usr/share/package-licenses/aardvark-dns/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/aardvark-dns/a2f60339450a52e61c6c1e27dc44bd1e671ad28e
/usr/share/package-licenses/aardvark-dns/a4692c5ae019f8bf1695b9c8b4e0ccae899b6e80
/usr/share/package-licenses/aardvark-dns/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/aardvark-dns/a74c5e048f9ed570eb892f81ca5daf05936475b0
/usr/share/package-licenses/aardvark-dns/a81399b7c3ec2d4619848fd59c11d21211fc3b86
/usr/share/package-licenses/aardvark-dns/bb8a9c551056a487e6bde6b31115ae45a9b9b802
/usr/share/package-licenses/aardvark-dns/bb92c62835916e922667b4fe181beed0e6efca91
/usr/share/package-licenses/aardvark-dns/c145b1a607ecf06aed81f1d04a65c2e43dffdc63
/usr/share/package-licenses/aardvark-dns/c54e008a9d57391b98e60b14c8dc524acd7b2df9
/usr/share/package-licenses/aardvark-dns/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/aardvark-dns/c71b43677c4ac8205f6eb573a073ea8e6df60c91
/usr/share/package-licenses/aardvark-dns/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/aardvark-dns/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/aardvark-dns/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/aardvark-dns/d3f4001d9de83a122956c9195d73e2507bf6c533
/usr/share/package-licenses/aardvark-dns/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/aardvark-dns/d7922ed0153e53eb7d63ea3fcae1040472c67679
/usr/share/package-licenses/aardvark-dns/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/aardvark-dns/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/aardvark-dns/e7b32657d4608cb4a57afa790801ecb9c2a037f5
/usr/share/package-licenses/aardvark-dns/e81567c196622efa36b46c5fd53cde741aaf0993
/usr/share/package-licenses/aardvark-dns/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/aardvark-dns/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
/usr/share/package-licenses/aardvark-dns/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb
/usr/share/package-licenses/aardvark-dns/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/aardvark-dns/f2d93b43d5bc8666a7978f9e71d7477d730a10c4
/usr/share/package-licenses/aardvark-dns/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/aardvark-dns/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/aardvark-dns/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/aardvark-dns/ff44b187892fcf1cd15a3ca61b498041b28afecc
/usr/share/package-licenses/aardvark-dns/ffffe83fef2bd6576c95e851bc81e1f6a641d638
